# Generated by Django 3.2.3 on 2021-06-15 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210615_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='description',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
