# Generated by Django 3.2.3 on 2021-08-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210809_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursetime',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='times',
            field=models.ManyToManyField(blank=True, related_name='times', to='api.CourseTime'),
        ),
    ]
