# Generated by Django 3.2.3 on 2021-08-22 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0003_alter_user_name'),
        ('api', '0007_auto_20210809_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewedCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_courses', to='user_api.user')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='api.course')),
            ],
        ),
    ]
